### PR TITLE
Input module

### PR DESCRIPTION
**Pull request by Gskartwii**
Get testing!

### CODE REVIEW

**Comment by eLunate** [comment]
This can't be merged yet, until Roblox either sorts out its BindableEvent issue or an alternative is implemented.

**Comment by Gskartwii** [comment]
It's still good to have the PR open for discussion and updates

**Comment by eLunate** [comment]
I'll actually look at implementing an alternative to events, if you're not already looking at one?

coroutine.wrap() or spawn()?

**Comment by Gskartwii** [comment]
Depends on the purpose. I would think coroutines when there is a need for instant action, and `spawn` when it doesn't matter.

**Comment by eLunate** [comment]
I'll make a module in bleeding-edge for it as ValkyrieEvents. Feel free to provide a better name if you have one.

**Comment by Gskartwii** [comment]
For reference: Anaminus/roblox-bug-tracker#740

**Comment by eLunate** [comment]
The module loads fine and is suitable for merging to bleeding edge and into dev

**Pull request merged**
