### PR TITLE
__div to index SharedVariables[Appbar/Sidebar]

### PR DESCRIPTION
**Pull request by Gskartwii**
Opening this PR for discussion and to remind me that I need to test this.

### CODE REVIEW

**Comment by eLunate** [comment]
Does it work?

Also does it have documentation? We should probably make sure that we have adequate documentation for new implementations before we merge them.

**Comment by Gskartwii** [comment]
I opened this pull request to remind me (or whoever would like) to test it. And yeah I should probably write the docs.

**Comment by Gskartwii** [comment]
Assigning @Temppeliherra to test this.

**Comment by Gskartwii** [comment]
This did cause the syntax problems I was afraid of:
``` lua
self/'Raw':Destroy(); -- error
(self/'Raw'):Destroy(); -- fine
```
Probably not worth it.

**Pull request closed without merging**
